name: run-docker-compose
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Run Docker Compose
        run: docker-compose up -d --force-recreate --build

